### ISSUE TITLE
[System Request] - Nintendo 3DS

### ISSUE THREAD

**Issue by rsubtil** [Zenjir0/es-theme-ComicBook#2]
Hey, I'm glad to see someone picked up this awesome theme and kept improving it, thanks for your work :smile: 

Would it be possible to add a 3DS theme? Retroarch now supports Citra, so I wanted to be able to boot my 3DS from EmulationStation.

**Comment by Zenjir0** [comment]
Sorry for the late response. I do already have a 3DS queued up ready to release when the next RetroPie releases.

System Image:
![system](https://user-images.githubusercontent.com/27794756/75213871-85fede00-5759-11ea-92a0-5cf1e5b2a370.png)

Comic Image:
![comic](https://user-images.githubusercontent.com/27794756/75213877-8b5c2880-5759-11ea-9984-6e7c27cfd548.png)

**Comment by Zenjir0** [comment]
@Ev1lbl0w If you have any recommendations or requests to change anything let me know. I am open to suggestions.

**Comment by rsubtil** [comment]
It looks awesome! Thanks for your hard work!

**Comment by Zenjir0** [comment]
This has been officially added in the 3.2-Beta
