### ISSUE TITLE
[System Request] - Wiiware

### ISSUE THREAD

**Issue by iwubcode** [Zenjir0/es-theme-ComicBook#3]
This is beyond gorgeous!

Please add the following additional system / libraries:

-   Nintendo Switch
-   Nintendo Wiiware (technically a part of "Wii" but many themes have it as a separate system)
-   Nintendo 3DS

I don't have any specific screenshots for use.  But if you need recommendations, let me know!

**Comment by Zenjir0** [comment]
I've already added both 3DS and Switch, you can try them out on the 3.2-Beta.
https://github.com/Zenjir0/es-theme-ComicBook/tree/3.2-Beta

Wiiware is a good one to add. I will add it to my ever growing list. 

Thank you for your suggestions.

**Comment by Zenjir0** [comment]
@iwubcode I plan on getting this done within the next week and add it to the master branch. Are there any specific Wiiware titles you would like to see, in the comic background?

**Comment by iwubcode** [comment]
@Zenjir0 - cool, thanks for doing this!

I think I'd go one of two ways:

* Highlight the popular wiiware games at the time, ex:  *Lost Winds*, *World of Goo*, *Megaman 9*, etc
* Highlight the unique experiences currently only found on Wiiware:  the Konami "Rebirth" games (*Star Soldier R*, *Contra Rebirth*, etc), *You, Me, and the Cubes*, *Jett Rocket*, *Muscle March*, etc

I don't have a preference on which approach you want to do and you could also mix-n-match.  Up to you!

**Comment by Zenjir0** [comment]
System Image: 
![system](https://user-images.githubusercontent.com/27794756/83363026-9096c800-a385-11ea-9497-8df1a3a2088c.png)

Comic:
![comic](https://user-images.githubusercontent.com/27794756/83363033-9ee4e400-a385-11ea-899b-db493293a283.png)

Comic Rip:
![comic_rip](https://user-images.githubusercontent.com/27794756/83363043-aefcc380-a385-11ea-8678-d5afa1719b53.png)

Thoughts?

**Comment by Zenjir0** [comment]
What it looks like in EmulationStation:

![2020-05-31 17_36_16-EmulationStation](https://user-images.githubusercontent.com/27794756/83363192-f6d01a80-a386-11ea-96cf-ccc78f894243.png)

**Comment by iwubcode** [comment]
Gorgeous!  Thank you so much

**Comment by Zenjir0** [comment]
I've added it to the main branch. Closing Ticket.

#37
