### ISSUE TITLE
Pac-man custom collection bannerlogo just shows up as white in the theme

### ISSUE THREAD

**Issue by rodclemen** [Zenjir0/es-theme-ComicBook#39]
I don't know if its just on my system (pi4b) but the pacman bannerlogo just shows as a white box.

I fixed it by downsizing it (made it 1000px which I think is still plenty big)

![bannerlogo](https://user-images.githubusercontent.com/66257773/83414798-5cbbb100-a41e-11ea-9541-f51d3fd17b4c.png)

**Comment by Zenjir0** [comment]
Yeah it was pretty big. Even though it is only 108KB, it's resolution was absurdly high. I pushed your edit of the logo to master just now. d64cb6b21f1a2eb268621897f2ab91c0f07155e8

**Comment by Zenjir0** [comment]
I've actually recently learned a few things about how the file size of the image impacts the memory on the Raspberry Pi devices. So if you happen to find anymore feel free to mention them here. I do plan on going through and making sure all my images are appropriate sizes.

**Comment by rodclemen** [comment]
I will :) and in case you don't know, you can save some insane space using something like https://tinypng.com.

**Comment by Zenjir0** [comment]
Oh I know. I use [PNGquant](https://pngquant.org/)/[Pngyu](https://nukesaq88.github.io/Pngyu/) but it does not resize the image it only "compresses" or in reality it just removes redundant data, and uses dithering.
